### ISSUE TITLE
AttributeError: 'com.ziclix.python.sql.PyConnection' object has no attribute 'dbms_ver'

### ISSUE THREAD

**Issue by brady-vitrano** [ibmdb/python-ibmdbsa#10]
Using `jython 2.7.0` and `jt400.jar`, I am receiving this error on first attempts using `engine.connect()`.

I can get the connection to work on a second attempt by catching the initial exception.

``` python
engine = create_engine('db2+zxjdbc400://user:pass@as400;prompt=false')
try:
    # this will fail
    connection = engine.connect()
except AttributeError:
    # this will pass
    connection = engine.connect()
```

**Comment by jazlee** [comment]
You need to use with connection string format like this:

`engine = create_engine('db2+zxjdbc400://user:pass@host/catalog')`

for example:

`user:password@192.168.0.1/S06D9787`
