### ISSUE TITLE
df.to_sql(table,engine,schem,if_exists('replace'),...)

### ISSUE THREAD

**Issue by jsiebrand** [ibmdb/python-ibmdbsa#102]
When will ibm_db_sa be updated to work with latest versions of SQLAlchemy, particularly 1.4.x?   I am using this as part of CP4D.

As the "replace" fails here:

~/jupyter_env/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py in get_pk_constraint(self, table_name, schema, **kw)
    527         with self._operation_context() as conn:
    528             return self.dialect.get_pk_constraint(
--> 529                 conn, table_name, schema, info_cache=self.info_cache, **kw
    530             )
    531 

~/jupyter_env/lib64/python3.6/site-packages/sqlalchemy/engine/interfaces.py in get_pk_constraint(self, connection, table_name, schema, **kw)
    282 
    283         """
--> 284         raise NotImplementedError()
    285 
    286     def get_foreign_keys(self, connection, table_name, schema=None, **kw):

NotImplementedError:

**Comment by amukherjee28** [comment]
The new release 0.3.7 supported to work with SQLAlchemy version 1.4.x.

Thanks.
