### ISSUE TITLE
AS400 Dialect Reflection does not recognize column TIMESTMP

### ISSUE THREAD

**Issue by brady-vitrano** [ibmdb/python-ibmdbsa#11]
I get the following error when running `engine.get_columns` on a table:

```
reflection.py:608: SAWarning: Did not recognize type 'TIMESTMP' of column`
```

**Comment by c-thiel** [comment]
To give a quick workaround for this:
`ibm_db_sa.base.ischema_names["TIMESTMP"] = ibm_db_sa.base.TIMESTAMP`

**Comment by bimalkjha** [comment]
@c-thiel Feel free to open pull request with fix. thanks.

**Comment by amukherjee28** [comment]
Will need a bit more details on this issue.
1. Could you please provide the table structure that is being fetched.
2. What is the server type from which the table is being fetched. (ZOS, LUW or IBMi)

Also will it possible to get the full error that was seen.

Thanks

**Comment by amukherjee28** [comment]
Will need a bit more details on this issue.
1. Could you please provide the table structure that is being fetched.
2. What is the server type from which the table is being fetched. (ZOS, LUW or IBMi)

Also will it possible to get the full error that was seen.

Thanks

**Comment by amukherjee28** [comment]
As per IBM documentation on IBM i datatype TIMESTAMP is the supported datatype.
https://www.ibm.com/docs/en/i/7.4?topic=formats-timestamp-data-type

Hence the base code is supported for the same datatype.
Any additional modification to datatype or special datatype has to be handled separately in the application code.

Above example provided looks a good way to handle any special case for datatypes.

Hence closing on the issue.
