### ISSUE TITLE
'ibm_db_sa.pyodbc.AS400Dialect_pyodbc' error

### ISSUE THREAD

**Issue by upenbendre** [ibmdb/python-ibmdbsa#115]
I am running an Apache SuperSet docker container, which has the packages below:

ibm-db                 3.1.4
ibm-db-sa              0.3.7
SQLAlchemy             1.4.21
SQLAlchemy-Utils       0.38.3

It is supposed to connect to a DB2 AIX database as a data source. Although it connects, I get this error:
Unable to load SQLAlchemy dialect <class 'ibm_db_sa.pyodbc.AS400Dialect_pyodbc'>: No module named 'sqlalchemy.connectors.zxJDBC'
2022-11-28 09:56:10,993:WARNING:superset.db_engine_specs:Unable to load SQLAlchemy dialect <class 'ibm_db_sa.pyodbc.AS400Dialect_pyodbc'>: No module named 'sqlalchemy.connectors.zxJDBC'

As per this https://github.com/ibmdb/python-ibmdbsa/issues/98#issuecomment-882403747 I have compatible versions that should clear this error, but that is not the case. These packages are needed so that Apache Superset can connect to a DB2 AIX database.

Also the ibm_db_sa driver is not able to read the DB2 AIX catalog, and retrieve the table and view names.

**Comment by bimalkjha** [comment]
@upenbendre Please use ibm-db-sa 0.3.9 and verify the issue. Thanks.
