### ISSUE TITLE
`sqlalchemy.types.String.RETURNS_CONDITIONAL` is undefined

### ISSUE THREAD

**Issue by eonu** [ibmdb/python-ibmdbsa#123]
I receive the following error when trying to create an engine with `ibm_db==3.1.4`, `ibm_db_sa==0.3.9` and `sqlalchemy==2.0.7` (on Mac M1).

```
>>> import sqlalchemy
>>> url = sqlalchemy.URL.create(drivername="db2", username="db2inst1", password="test", database="test", host="localhost", port="50000")
>>> engine = sqlalchemy.create_engine(url)
Traceback (most recent call last):
  ...
  File "/Users/eonu/env/test/lib/python3.8/site-packages/ibm_db_sa/__init__.py", line 22, in <module>
    from . import ibm_db, pyodbc, base
  File "/Users/eonu/env/test/lib/python3.8/site-packages/ibm_db_sa/ibm_db.py", line 20, in <module>
    from .base import DB2ExecutionContext, DB2Dialect
  File "/Users/eonu/env/test/lib/python3.8/site-packages/ibm_db_sa/base.py", line 662, in <module>
    class DB2Dialect(default.DefaultDialect):
  File "/Users/eonu/env/test/lib/python3.8/site-packages/ibm_db_sa/base.py", line 675, in DB2Dialect
    returns_unicode_strings = sa_types.String.RETURNS_CONDITIONAL
AttributeError: type object 'String' has no attribute 'RETURNS_CONDITIONAL'
```

Seems to be failing at the following conditional:

https://github.com/ibmdb/python-ibmdbsa/blob/99c5451a3d9ee2faa990747dfb70fdfed375ab33/ibm_db_sa/base.py#L672-L675

In the SQLAlchemy version that I'm using (2.0.7), `sqlalchemy.types.String.RETURNS_CONDITIONAL` seems to be undefined.

```
>>> import sqlalchemy
>>> sqlalchemy.__version__
'2.0.7'
>>> sqlalchemy.types.String.RETURNS_CONDITIONAL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'String' has no attribute 'RETURNS_CONDITIONAL'
```

**Comment by bchoudhary6415** [comment]
@eonu ibm_db_sa do not support SQLAlchemy 2.0 yet. The documented version of SQLAlchemy is 1.4.x, so you need to downgrade your SQLAlchemy version. We are working on enhancement to support sqlalchemy 2.0 and once the support get released, you can use that. Thanks.

**Comment by eonu** [comment]
Thanks! In that case, is it worth specifying `sqlalchemy>=0.7.3,<2.0` in `setup.py` until SQLAlchemy 2.0 is supported?

**Comment by bchoudhary6415** [comment]
@eonu  
It's mentions that 
SQLAlchemy version between 0.7.3 - 1.4.x.

**Comment by eonu** [comment]
> @eonu It's mentions that SQLAlchemy version between 0.7.3 - 1.4.x.

I see that it is mentioned in README.md, but adding it to `setup.py` may make it clearer to users that SQLAlchemy >= 2 is unsupported – `pip install` would fail if they had an incompatible SQLAlchemy version. Just a suggestion!

**Comment by bchoudhary6415** [comment]
@eonu Thanks for your suggestion!
I will discuss with my team on this.

**Comment by anthobio23** [comment]
Too can use version 1.3.24 if the version of ibm_db is the lastest

**Comment by bchoudhary6415** [comment]
@eonu The fix for this issue is given. Please verify through the latest PR - https://github.com/ibmdb/python-ibmdbsa/pull/124
I'm closing this issue now.
Thank you
