### ISSUE TITLE
Support to SQLAlchemy 2.X

### ISSUE THREAD

**Issue by frbelotto** [ibmdb/python-ibmdbsa#125]
Please update to support latest version of SQLA.

**Comment by cdracars** [comment]
+1

**Comment by bchoudhary6415** [comment]
@frbelotto and @cdracars We are currently in the process of making code changes to support the latest version of SQLAlchemy and are conducting thorough testing to ensure its compatibility and stability. Once this testing is complete and changes have been fully implemented, we will release a new version of ibm_db_sa. We appreciate your patience and understanding during this process.
Thank you

**Comment by cdracars** [comment]
Is there anything that I can do to help with this?  I don't want to just agree and not offer support.

**Comment by bchoudhary6415** [comment]
@cdracars 
Thank you for offering your support. 
At this time, we are working on implementing the necessary changes to support the latest version of SQLAlchemy.
However, if you have any expertise or experience with SQLAlchemy or ibm_db_sa, we would greatly appreciate any insights or suggestions you may have.
Please feel free to share any relevant knowledge or resources with us.
We value your input and support in this process.
Thank you again.

**Comment by bchoudhary6415** [comment]
@frbelotto and @cdracars 
Support to SQLAlchemy 2.0.x is now given in new released ibm_db_sa v0.4.0.

Thank you
