### ISSUE TITLE
Simple queries extremely slow to return

### ISSUE THREAD

**Issue by awlamb** [ibmdb/python-ibmdbsa#13]
Running this query with sqlalchemy:

```
SELECT live.videos.place_id AS place_id
FROM live.videos
WHERE date(live.videos.create_dt) = ? AND live.videos.place_id <= ? ORDER BY live.videos.place_id DESC FETCH FIRST 10 ROWS ONLY
```

So slow it times out. This does, however, run in one second or so on a SQL browser. I feel like this may be a driver issue but i'm not sure how to go about debugging it.

**Comment by hemlatabhatt** [comment]
Please re-open with more details .
