### ISSUE TITLE
Error : NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:db2.ibm_db

### ISSUE THREAD

**Issue by raviteja540** [ibmdb/python-ibmdbsa#138]
Hi, I am using Mac M1 chip , I am facing issues connecting to ibm db2 which is on cloud via sqlAIchemy using LanghChain. 

I have installed ibm_db and ibm_db_sa but getting below error : 

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:db2.ibm_db

version : 
Name: SQLAlchemy
Version: 2.0.23
Name: ibm-db-sa
Version: 0.4.0
Name: ibm-db
Version: 3.2.0
Python 3.9.11

**Comment by bchoudhary6415** [comment]
Given update:
Please follow the below steps to install ibm_db on mac M1 chip, than install ibm_db_sa
https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#m1chip
