### ISSUE TITLE
SQL syntax error when using limit on an Informix database

### ISSUE THREAD

**Issue by joseajunior** [ibmdb/python-ibmdbsa#139]
I'm using SqlAlchemy 2.0 with Informix database using ibm_db_sa, I'm doing a select statement using the limit clause and it's showing an SQL syntax error.

While I was debugging this error using ` echo=True `, I noticed that the ` limit_clause ` is adding a ` FETCH FIRST n ROWS ONLY ` to the SQL statement but this doesn't work for my database, It needs to add ` LIMIT n `.

**Comment by bchoudhary6415** [comment]
@joseajunior As ibm_db_sa doesn't support informix database
The supported database list by ibm_db_sa is mentioned here https://github.com/ibmdb/python-ibmdbsa#supported-databases

Thank you
