### ISSUE TITLE
Correct Homepage / Download Link on pypi

### ISSUE THREAD

**Issue by dwt** [ibmdb/python-ibmdbsa#141]
I just noticed that [the pypi listing](https://pypi.org/project/ibm-db-sa/) doesn't point to this repo, but instead [links to the db driver project via an indirection on google code](http://code.google.com/p/ibm-db/downloads/list).

I'm pretty sure this is very much outdated.

I would like to recommend to actually link GitHub directly, either as gihthub or as the homepage. Either remove the download link or let it point to the GitHub releases page.

**Comment by bchoudhary6415** [comment]
Hello @dwt 
Yes the pypi link - https://pypi.org/project/ibm-db-sa/
in Project links - download section suggesting python-ibmdb link (https://github.com/ibmdb/python-ibmdb).
Will try to update it with correct link of ibm_db_sa ( https://github.com/ibmdb/python-ibmdbsa) in next release.

Thank you so much for pointing it out.
