### ISSUE TITLE
Add release notes / changelog to GitHub releases

### ISSUE THREAD

**Issue by dwt** [ibmdb/python-ibmdbsa#142]
They are currently missing, making it hard to discover what changed and whether one needs or wants to update.

**Comment by bchoudhary6415** [comment]
Hello @dwt 
You can find the changed notes here - https://github.com/ibmdb/python-ibmdbsa/blob/master/CHANGES.md
Thanks

**Comment by bchoudhary6415** [comment]
Hello @dwt 
Any update on this issue?
Or should we close this one?

Thanks

**Comment by bchoudhary6415** [comment]
Hello @dwt 
Since you haven't provided an update.
I'm closing this issue for now.
If you have something, feel free to reopen this issue.

Thanks

**Comment by dwt** [comment]
actually, now that I re-read the issue, I was hoping for you to show the release notes here as part of the releases: https://github.com/ibmdb/python-ibmdbsa/releases That would be really help to make them more discoverable and promote them.

Having them in the repo as `Changes.md` is also quite a good start though.
