### ISSUE TITLE
Error  Can't load plugin: sqlalchemy.dialects:ibm_db_sa

### ISSUE THREAD

**Issue by FernandoGuinLeite** [ibmdb/python-ibmdbsa#143]
I have the following error Can't load plugin: sqlalchemy.dialects:ibm_db_sa in the jupyter compiler it works normally.
However, when I transform it into an executable, the error I mentioned above occurs.
The line I use to transform it into .exe is this pyinstaller --onefile nomeDoApp.py

**Comment by bchoudhary6415** [comment]
Hello @FernandoGuinLeite 
Can you please share the steps to reproduce this issue?
If possible, please share a sample script so that I can run it on my system and try to reproduce it. 

Thanks

**Comment by FernandoGuinLeite** [comment]
Good morning, how are you? Follow my code below.

from tqdm import tqdm
import sys
import os
sys.path.append(r'C:\Users\fleite\App\Ferramentas_customizadas')
import integrador_hanna_e_DB2
import pandas as pd
import ibm_db_dbi
import ibm_db
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import create_engine, text
db_origem_uri = 'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'
db_destino_uri = 'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'

# Tentar conectar ao banco de origem
try:
    engine_origem = create_engine(db_origem_uri)
    print('Banco origem conectado')
except Exception as e:
    print(f'Erro ao conectar ao banco de origem: {e}')

# Tentar conectar ao banco de destino
try:
    engine_destino = create_engine(db_destino_uri)
    print('Banco destino conectado')
except Exception as e:
    print(f'Erro ao conectar ao banco de destino: {e}')

def process_schema_table():
    while True:
        try:
            schema = input('Digite o schema da Tabela:').strip().upper()
            tabela = input('Digite o nome da tabela:').strip().upper()
            schema_tabela_concatenar = f"{schema}.{tabela}"
            
            if schema_tabela_concatenar == 'RCHUMANO.VEN_DES_ANO_GRH':
                ano_mes_civil = input('Digite o Ano Mes Civil: ').strip()
                select_origem = f"""
                SELECT * from RCHUMANO.VEN_DES_ANO_GRH
                where ano_mes_civil > {ano_mes_civil}
                """
                result_origem = pd.read_sql(select_origem, engine_origem)
            else:
                select_origem = f'SELECT * FROM {schema_tabela_concatenar}'
                result_origem = pd.read_sql(select_origem, engine_origem)
            
            # Executar a instrução DELETE antes do INSERT
            with engine_destino.begin() as conn:
                sql_delete = text(f"DELETE FROM {schema_tabela_concatenar}")
                conn.execute(sql_delete)
                print("Consulta DELETE executada com sucesso.")

                # Preparar dados para inserção
                rows_to_insert = []
                for index, row in tqdm(result_origem.iterrows(), total=len(result_origem), desc="Inserindo dados"):
                    row_dict = row.to_dict()
                    insert_values = {col: val if not pd.isnull(val) else None for col, val in row_dict.items()}
                    rows_to_insert.append(insert_values)
            
                # Executar a instrução de inserção em lote
                insert_statement = text(
                    f"INSERT INTO {schema_tabela_concatenar}"
                    f"({', '.join(result_origem.columns)}) "
                    f"VALUES ({', '.join([':' + col for col in result_origem.columns])})"
                )
                conn.execute(insert_statement, rows_to_insert)
                conn.commit()  # Commit da transação para efetivar as alterações
                print("Dados inseridos com sucesso na tabela de destino.")
            
            break  # Sair do loop após sucesso
        except Exception as e:
            if 'SQLCODE=-551' in str(e):
                print("Erro de privilégio: Você não tem autorização para acessar essa tabela entre em contato com o administrador do banco.")
            elif 'SQLCODE=-204' in str(e):
                print("Erro de tabela inexistente: Por favor digite o schema e tabela válidos.")
            elif 'SQLCODE=-104' in str(e):
                print("Erro tabela em branco: Por favor digite o schema e tabela válidos.")
            else:
                print(f"Erro: {e}")
            input("Pressione Enter para continuar...")

# Loop para continuar solicitando os inputs após inserção bem-sucedida
while True:
    process_schema_table()
    continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
    while continuar not in ['S', 'N']:
        print("Opção inválida. Por favor, digite 'S' para sim ou 'N' para não.")
        continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
    if continuar != 'S':
        break

This code in my jupyter is working normally

However, when I transform it into executable it gives the following error below
Error Unable to load plugin: sqlalchemy.dialects:ibm_db_sa
.

The way I generate the executable is with the lines below

pyinstaller --onefileProgramName.py

**Comment by FernandoGuinLeite** [comment]
Good morning, how are you? Follow my code below.

from tqdm import tqdm
import sys
import os
sys.path.append(r'C:\Users\fleite\App\Ferramentas_customizadas')
import integrador_hanna_e_DB2
import pandas as pd
import ibm_db_dbi
import ibm_db
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import create_engine, text
db_origem_uri = 'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'
db_destino_uri = 'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'


try:
engine_origem = create_engine(db_origem_uri)
print('Banco origem conectado')
except Exception as e:
print(f'Erro ao conectar ao banco de origem: {e}')

try:
engine_destino = create_engine(db_destino_uri)
print('Banco destino conectado')
except Exception as e:
print(f'Erro ao conectar ao banco de destino: {e}')

def process_schema_table():
while True:
try:
schema = input('Digite o schema da Tabela:').strip().upper()
tabela = input('Digite o nome da tabela:').strip().upper()
schema_tabela_concatenar = f"{schema}.{tabela}"

        if schema_tabela_concatenar == 'RCHUMANO.VEN_DES_ANO_GRH':
            ano_mes_civil = input('Digite o Ano Mes Civil: ').strip()
            select_origem = f"""
            SELECT * from RCHUMANO.VEN_DES_ANO_GRH
            where ano_mes_civil > {ano_mes_civil}
            """
            result_origem = pd.read_sql(select_origem, engine_origem)
        else:
            select_origem = f'SELECT * FROM {schema_tabela_concatenar}'
            result_origem = pd.read_sql(select_origem, engine_origem)
        
    
        with engine_destino.begin() as conn:
            sql_delete = text(f"DELETE FROM {schema_tabela_concatenar}")
            conn.execute(sql_delete)
            print("Consulta DELETE executada com sucesso.")


            rows_to_insert = []
            for index, row in tqdm(result_origem.iterrows(), total=len(result_origem), desc="Inserindo dados"):
                row_dict = row.to_dict()
                insert_values = {col: val if not pd.isnull(val) else None for col, val in row_dict.items()}
                rows_to_insert.append(insert_values)
        

            insert_statement = text(
                f"INSERT INTO {schema_tabela_concatenar}"
                f"({', '.join(result_origem.columns)}) "
                f"VALUES ({', '.join([':' + col for col in result_origem.columns])})"
            )
            conn.execute(insert_statement, rows_to_insert)
            conn.commit()  # Commit da transação para efetivar as alterações
            print("Dados inseridos com sucesso na tabela de destino.")
        
        break  
    except Exception as e:
        if 'SQLCODE=-551' in str(e):
            print("Erro de privilégio: Você não tem autorização para acessar essa tabela entre em contato com o administrador do banco.")
        elif 'SQLCODE=-204' in str(e):
            print("Erro de tabela inexistente: Por favor digite o schema e tabela válidos.")
        elif 'SQLCODE=-104' in str(e):
            print("Erro tabela em branco: Por favor digite o schema e tabela válidos.")
        else:
            print(f"Erro: {e}")
        input("Pressione Enter para continuar...")

while True:
process_schema_table()
continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
while continuar not in ['S', 'N']:
print("Opção inválida. Por favor, digite 'S' para sim ou 'N' para não.")
continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
if continuar != 'S':
break

This code in my jupyter is working normally

However, when I transform it into executable it gives the following error below
Error Unable to load plugin: sqlalchemy.dialects:ibm_db_sa
.

The way I generate the executable is with the lines below

pyinstaller --onefileProgramName.py

**Comment by bchoudhary6415** [comment]
Hello @FernandoGuinLeite 
You have not imported ibm_db_sa in your code.
Please give
import ibm_db_sa
and try running the code.

Thanks

**Comment by FernandoGuinLeite** [comment]
I performed the import in my code.
My code below

from tqdm import tqdm
import sys
import os
sys.path.append(r'C:\xxx\xxx\xxx\xxx')
import integrador_hanna_e_DB2
import pandas as pd
import ibm_db_dbi
import ibm_db
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy import create_engine, text
import ibm_db_sa
db_origem_uri =  'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'
db_destino_uri = 'ibm_db_sa://xxx:xxx@xxx:xxx/xxx'


try:
    engine_origem = create_engine(db_origem_uri)
    print('Banco origem conectado')
except SQLAlchemyError as e:
    print(f'Erro ao conectar ao banco de origem: {e}')


try:
    engine_destino = create_engine(db_destino_uri)
    print('Banco destino conectado')
except SQLAlchemyError as e:
    print(f'Erro ao conectar ao banco de destino: {e}')

    def process_schema_table():
    while True:
        try:
            schema = input('Digite o schema da Tabela:').strip().upper()
            tabela = input('Digite o nome da tabela:').strip().upper()
            schema_tabela_concatenar = f"{schema}.{tabela}"

            if schema_tabela_concatenar == 'RCHUMANO.VEN_DES_ANO_GRH':
                ano_mes_civil = input('Digite o Ano Mes Civil: ').strip()
                select_origem = f"""
                SELECT * from RCHUMANO.VEN_DES_ANO_GRH
                where ano_mes_civil > {ano_mes_civil}
                """
                result_origem = pd.read_sql(select_origem, engine_origem)
            else:
                select_origem = f'SELECT * FROM {schema_tabela_concatenar}'
                result_origem = pd.read_sql(select_origem, engine_origem)


            with engine_destino.begin() as conn:
                sql_delete = text(f"DELETE FROM {schema_tabela_concatenar}")
                conn.execute(sql_delete)
                print("Consulta DELETE executada com sucesso.")


                rows_to_insert = []
                for index, row in tqdm(result_origem.iterrows(), total=len(result_origem), desc="Inserindo dados"):
                    row_dict = row.to_dict()
                    insert_values = {col: val if not pd.isnull(val) else None for col, val in row_dict.items()}
                    rows_to_insert.append(insert_values)


                insert_statement = text(
                    f"INSERT INTO {schema_tabela_concatenar}"
                    f"({', '.join(result_origem.columns)}) "
                    f"VALUES ({', '.join([':' + col for col in result_origem.columns])})"
                )
                conn.execute(insert_statement, rows_to_insert)
                conn.commit()  # Commit da transação para efetivar as alterações
                print("Dados inseridos com sucesso na tabela de destino.")


                print(f"Número total de linhas inseridas: {len(rows_to_insert)}")

            break
        except Exception as e:
            if 'SQLCODE=-551' in str(e):
                print("Erro de privilégio: Você não tem autorização para acessar essa tabela entre em contato com o administrador do banco.")
            elif 'SQLCODE=-204' in str(e):
                print("Erro de tabela inexistente: Por favor digite o schema e tabela válidos.")
            elif 'SQLCODE=-104' in str(e):
                print("Erro tabela em branco: Por favor digite o schema e tabela válidos.")
            else:
                print(f"Erro: {e}")
            input("Pressione Enter para continuar...")


while True:
    process_schema_table()
    continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
    while continuar not in ['S', 'N']:
        print("Opção inválida. Por favor, digite 'S' para sim ou 'N' para não.")
        continuar = input("Deseja inserir outra tabela? (S/N): ").strip().upper()
    if continuar != 'S':
        break

No compiler the code is working perfectly.
I use Jupyter as a compiler.
What happens is when I generate the .exe file the error below occurs

Error connecting to the source database: Can't load plugin: sqlalchemy.dialects:ibm_db_sa

**Comment by FernandoGuinLeite** [comment]
Bom dia tudo bem?
Realizei o comando e meu arquivo .exe funcionou corretamente muito obrigao
att,

Em qui., 16 de mai. de 2024 às 07:51, bchoudhary6415 <
***@***.***> escreveu:
