### ISSUE TITLE
Support for informix DB

### ISSUE THREAD

**Issue by pabloh007** [ibmdb/python-ibmdbsa#16]
Currently some errors arise when trying to to use this dialect for Informix DB. Is there plans to support informix db as well under this dialect or will a new one be created?

**Comment by igna-v** [comment]
Is there an update on this?

**Comment by amukherjee28** [comment]
Hi,

We Supported I-series and ZOS connection in our last release.
Currently as we plan for the next release we will consider this request.

I will keep you posted for more details on the same.

Thanks.

**Comment by bimalkjha** [comment]
This adaptor do not support Informix server and we have no plan to add that support as of now. Thanks.
