### ISSUE TITLE
Python Decimal to Decimal SA to Decimal Column casting problem

### ISSUE THREAD

**Issue by ericpershey** [ibmdb/python-ibmdbsa#17]
Given a python Decimal(54000000000000), when you put it into a Decimal column in SQLAlchemy that maps to a DB2 column, it adds extra data on it.   Version of ibm_db_sa is 0.3.3.  This has been seen on Mac, Windows and Linux.  
```
from pprint import pprint
from decimal import Decimal
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import scoped_session
from sqlalchemy.types import DECIMAL
from sqlalchemy.types import Integer
import ibm_db_sa
Base = declarative_base()

class TestTable(Base):
    __tablename__ = 'TEST_TABLE'
    __table_args__ = {'schema' : 'ALCF_TEST'}
    
    AUTO_GENERATED_ID = Column(Integer, primary_key=True)
    DECIMAL_26_6 = Column(DECIMAL)

def get_all_sa(session):
    tts = session.query(TestTable).all()
    for tt in tts:
        dct = {
               'DECIMAL_26_6':tt.DECIMAL_26_6,
               }
        pprint(dct)
    
def sa_test(username, password, host, port, database):
    dsn = '%s:%s@%s:%s/%s' % (username, password, host, port, database)
    engine = create_engine('ibm_db_sa://%s' % dsn)#, echo=True)
    conn = engine.connect()
    session = scoped_session(sessionmaker(bind=engine))
    
    tt = TestTable()
    n = Decimal(54000000000000)
    tt.DECIMAL_26_6 = n
    session.add(tt)
    session.commit()
    get_all_sa(session)
    conn.close()
        
if __name__ == "__main__":
    print(ibm_db_sa.__version__)
    username = ''
    password = ''
    host = ''
    port = 50001
    database = ""
    sa_test(username, password, host, port, database)    
```
When you select the data inserted you will get the following: Decimal('54000000000000.010000'), but you should get exactly Decimal(54000000000000).

Here is the SCHEMA for the table.
-- DROP TABLE ALCF_TEST.TEST_TABLE;
CREATE SCHEMA ALCF_TEST;
CREATE TABLE ALCF_TEST.TEST_TABLE (
  AUTO_GENERATED_ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  DECIMAL_26_6 DECIMAL(26, 6),
);

**Comment by hemlatabhatt** [comment]
Hi ,
can you please try by modifying the flag supports_native_decimal  to TRUE  in ibm_db.py file under ibm_db_sa.

class DB2Dialect_ibm_db(DB2Dialect):
    supports_native_decimal = True

Thanks

**Comment by ericpershey** [comment]
I can confirm this working on the following versions. 

('C:\\Python27\\lib\\site-packages\\ibm_db_sa\\__init__.pyc', '0.3.3')
(sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0), '2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]')

C:\Python35\lib\site-packages\ibm_db_sa\__init__.py 0.3.3
sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0) 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
