### ISSUE TITLE
lets add ability to produce columns reflection with comments

### ISSUE THREAD

**Issue by asierra01** [ibmdb/python-ibmdbsa#24]
sqlalchemy 12 has the capability to  add comment to a column definition

so if I create a table with comments describing the field

some_table = schema.Table( 'some_table', metadata,
      Column('some_field'             , Date,       nullable=False, index= True,unique=False,
             **comment = 'some comments about my column'**)
)

columns = sqlalchemy.engine.reflection.Inspector.from_engine(my_engine).get_columns('some_table','schema_name')

This columns dict returned by the Inspector will have a comment key with the column/field comments.

something like this will add this capability...
file reflection.py from ibm_db_sa

sys_columns = Table("COLUMNS", ischema,
      Column("TABSCHEMA", CoerceUnicode, key="tabschema"),
      Column("TABNAME", CoerceUnicode, key="tabname"),
      Column("COLNAME", CoerceUnicode, key="colname"),
      Column("COLNO", sa_types.Integer, key="colno"),
      Column("TYPENAME", CoerceUnicode, key="typename"),
      Column("LENGTH", sa_types.Integer, key="length"),
      Column("SCALE", sa_types.Integer, key="scale"),
      Column("DEFAULT", CoerceUnicode, key="defaultval"),
      Column("NULLS", CoerceUnicode, key="nullable"),
      Column("IDENTITY", CoerceUnicode, key="identity"),
      Column("GENERATED", CoerceUnicode, key="generated"),
      **Column("REMARKS", CoerceUnicode, key="remmarks"),**
      schema="SYSCAT")

on the function 
 def get_columns(self, connection, table_name, schema=None, **kw):

 query = sql.select([syscols.c.colname, syscols.c.typename,
                            syscols.c.defaultval, syscols.c.nullable,
                            syscols.c.length, syscols.c.scale,
                            syscols.c.identity, syscols.c.generated,
                            **syscols.c.remmarks**],
              sql.and_(
                  syscols.c.tabschema == current_schema,
                  syscols.c.tabname == table_name
                ),
              order_by=[syscols.c.colno]
            )

class DB2Reflector(BaseReflector):
                     'type': coltype,
                     'nullable': r[3] == 'Y',
                     'default': r[2] or None,
                    **'comment' : r[8] or None,**
                     'autoincrement': (r[6] == 'Y') and (r[7] != ' '),
                 })

**Comment by amukherjee28** [comment]
@asierra01 
The following link talks about syscat.columns meta data query in Db2 luw
https://www.ibm.com/docs/en/db2/11.5?topic=views-syscatcolumns

I see this can be implemented. Will incorporate the changes in the code and confirm.

Thanks.
