### ISSUE TITLE
add capability to the driver to generate query with literals, compile_kwargs={"literal_binds": True}

### ISSUE THREAD

**Issue by asierra01** [ibmdb/python-ibmdbsa#25]
if I create a query

  s_with_table_name = select([table_with_custom_columns]).\
            where(table_with_custom_columns.c.some_custom_column == "IBM")

   mylog.info( "result of the compilation specifying table name \n\n%s\n" % s_with_table_name)
      my_str_db2 = s_with_table_name.compile(
         dialect=ibm_db_sa.dialect(),
         **compile_kwargs={"literal_binds": True}**)

 Now the driver error out on this, other sa drivers produce a query with the literals

SELECT table_with_custom_columns.some_custom_column, table_with_custom_columns.id, table_with_custom_columns.some_id 
FROM table_with_custom_columns 
WHERE table_with_custom_columns.some_custom_column = **'IBM'**  

vs 

SELECT table_with_custom_columns.some_custom_column, table_with_custom_columns.id, table_with_custom_columns.some_id 
FROM table_with_custom_columns 
WHERE table_with_custom_columns.some_custom_column = **:some_custom_column_1**

to fix this

file base.py from ibm_db_sa driver

change function get_select_precolumns  signature 
from
def get_select_precolumns(self, select):

to
def get_select_precolumns(self, select,**kwargs):

as sqlalchemy compiler looks for a function with this signature when we compile with

**compile_kwargs={"literal_binds": True}**

it doesn't brake the code if compile_kwargs is not specify  on the compilation
  my_str_db2 = s_with_table_name.compile(
         dialect=ibm_db_sa.dialect())

**Comment by ericpershey** [comment]
as of 2018-01-08, this problem still exists within https://github.com/ibmdb/python-ibmdbsa/blob/master/ibm_db_sa/ibm_db_sa/base.py

**Comment by asierra01** [comment]
I forked the code ...see on my git forked code how to fix this. I guess I need to request a git pull so the ibm_db_sa officials mantainers can add this to the trunk .

**Comment by hemlatabhatt** [comment]
@asierra01  I have incorporated the fix in the ibm_db_sa code.
Thanks

**Comment by asierra01** [comment]
When I have a chance this weekend, let me do some tests. I also have other minor enhancements....

**Comment by asierra01** [comment]
I just found out there is another function, that needs **kwargs,  base.DB2Compiler

def limit_clause(self, select, ****kwargs**):

**Comment by blenard81** [comment]
Updated my PMR to fix this

**Comment by hemlatabhatt** [comment]
@asierra01,Thanks for contributing,I have incorporated the fix.

Regards
Hemlata
