### ISSUE TITLE
"No module named ibm_db_dbi"

### ISSUE THREAD

**Issue by keynator** [ibmdb/python-ibmdbsa#26]
Hi,

I cannot use your module since I get an main error. I took this is from your documentation

    from sqlalchemy import create_engine
    e = create_engine("db2+ibm_db://user:pass@host[:port]/database")
but get this error

    Traceback (most recent call last):
      File "ibm_db2_test3.py", line 2, in <module>
        e = create_engine("db2+ibm_db://user:pass@host:1111/database")
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 75, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/lib/python2.7/dist-packages/ibm_db_sa/ibm_db.py", line 58, in dbapi
        import ibm_db_dbi as module
    ImportError: No module named ibm_db_dbi

I can also use another engine (or same kind of alias)

    from sqlalchemy import create_engine
    import ibm_db_sa.ibm_db
    e = create_engine('ibm_db_sa://user:pass@host:1111/database')

with the same error. The system has the follwing properties:

- Debian Linux Strech 64bit
- Python 2.7 (as you see from the errors) in version 2.7.13-2 via apt
- Your lib is installed via apt as 'python-ibm-db-sa ' in recent version 0.3.0-3
- sqlalchemy via apt in version 1.0.15

Searching for "No module named ibm_db_dbi" via google shows some guys with the same problems but no real solution. Do you think that the Debian package is some kind of broken?

**Comment by hemlatabhatt** [comment]
@keynator  Can you share your pip list please.TIA

**Comment by keynator** [comment]
I have not used pip before but now installed pip and then did

    pip install ibm_db_sa
    pip install ibm_db

but before removed the debian package python-ibm-db-sa . Now it does work.
