### ISSUE TITLE
Don't work on AS400

### ISSUE THREAD

**Issue by ncastrog** [ibmdb/python-ibmdbsa#27]
Script:
import pandas as pd
from sqlalchemy import create_engine
import glob

csv=(glob.glob("/home/nahum/*.csv"))
df_csv = pd.DataFrame(csv)

for index, row in df_csv.iterrows():
    datastore=pd.read_csv(str(row[0]), delimiter=',', header=[0],skipfooter=3)
    engine = create_engine('ibm_db_sa://USUARIO:PASS@192.168.0.10/*local')
    datastore.to_sql('SCHEMACSV.conc', engine, if_exists='append', index=False)

Don't work on AS400 gives this error:
OperationalError: (ibm_db_dbi.OperationalError) ibm_db_dbi::OperationalError: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.16.0.78".  Communication function detecting the error: "connect".  Protocol specific error code(s): "111", "*", "*".  SQLSTATE=08001 SQLCODE=-30081

This code works on:
Postgresql, DB2 for Linux, Mysql... in all server but not on DB2 iseries.

**Comment by SabaKauser** [comment]
You would need to specify correct port where your iSeries server is listening to. in create_engine.
e.g: db2 =sqlalchemy.create_engine('ibm_db_sa://username:password@host:port/database').

Other connections works probably because you are not using remote client.
