### ISSUE TITLE
Getting error ImportError: No module named 'ibm_db_dbi'

### ISSUE THREAD

**Issue by sidnaik03** [ibmdb/python-ibmdbsa#34]
Hi,
I am using ibm_db_sa driver.My connection code is `"create_engine("db2+ibm_db://dbinst1:********@192.168.XX.XXX:XXXXX/sample",pool_size=20, echo=False, poolclass=QueuePool).connect()"`
When I am try to connect to db I got below error

> ImportError: No module named 'ibm_db_dbi'

Whats wrong with my code ?

**Comment by hemlatabhatt** [comment]
@sidnaik03 Can you share your pip list please.

**Comment by sidnaik03** [comment]
@hemlatabhatt 

amqp==2.2.2
billiard==3.5.0.3
BTrees==4.4.1
celery==4.1.0
cx-Oracle==6.1
ibm-db-sa==0.3.3
kombu==4.1.0
persistent==4.2.4.2
psycopg2==2.7.4
pymongo==3.6.1
pyodbc==4.0.22
pytz==2018.3
redis==2.10.6
six==1.11.0
SQLAlchemy==1.2.2
transaction==2.1.2
vine==1.1.4
zc.lockfile==1.2.1
ZConfig==3.2.0
ZODB==5.3.0
zodbpickle==1.0
zope.interface==4.4.3
zope.sqlalchemy==1.0

**Comment by hemlatabhatt** [comment]
@sidnaik03 Please do pip install ibm_db and retry.

**Comment by sidnaik03** [comment]
@hemlatabhatt 

pip install ibm_db gives following error. 

`Collecting ibm_db
  Using cached https://files.pythonhosted.org/packages/f8/6f/5f8186cb31021409235a948be5e29d77761ef92747a101360003747c4105/ibm_db-2.0.8.tar.gz
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... error
  Complete output from command /home/siddhesh/Envs/agentenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yra9wier/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-8dx4t69k --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-yra9wier/ibm-db/setup.py", line 17, in <module>
      os.rename('tests','test_2')
  OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
  
  ----------------------------------------
  Failed building wheel for ibm-db
  Running setup.py clean for ibm-db
  Complete output from command /home/siddhesh/Envs/agentenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yra9wier/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-yra9wier/ibm-db/setup.py", line 17, in <module>
      os.rename('tests','test_2')
  OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
  
  ----------------------------------------
  Failed cleaning build dir for ibm-db
Failed to build ibm-db
Installing collected packages: ibm-db
  Running setup.py install for ibm-db ... error
    Complete output from command /home/siddhesh/Envs/agentenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yra9wier/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hfsln98x/install-record.txt --single-version-externally-managed --compile --install-headers /home/siddhesh/Envs/agentenv/include/site/python3.5/ibm-db:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yra9wier/ibm-db/setup.py", line 17, in <module>
        os.rename('tests','test_2')
    OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
    
    ----------------------------------------
Command "/home/siddhesh/Envs/agentenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yra9wier/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hfsln98x/install-record.txt --single-version-externally-managed --compile --install-headers /home/siddhesh/Envs/agentenv/include/site/python3.5/ibm-db" failed with error code 1 in /tmp/pip-install-yra9wier/ibm-db/
`

Is there any other dependency ?

**Comment by hemlatabhatt** [comment]
@sidnaik03  Can you try easy_install ibm_db / pip install ibm_db==2.0.8a0 please?There is no dependency , its not picking the latest version from  pip .

**Comment by sidnaik03** [comment]
@hemlatabhatt Thanks. Now its worked. Thanks a lot. Have a great day.

**Comment by asmitaorpe** [comment]
type in requirements.txt as ibm_db

**Comment by tgtimoteo** [comment]
Hi, @hemlatabhatt , I having the same problem and tried the same. It didn't work. It keeps showing this: ImportError: No module named 'ibm_db_dbi'. I've also tried other versions of ibm_db. I'm new at that. Can you help me?
