### ISSUE TITLE
Add documentation on alchemy url for conncetion over ssl

### ISSUE THREAD

**Issue by raguks** [ibmdb/python-ibmdbsa#41]
I could not find documentation for ssl url and trust store location in url(format). Can you please add it? 

https://github.com/ibmdb/python-ibmdbsa/blob/6bc37aa81ca9117d5eb320ba0572f071fba85d89/ibm_db_sa/ibm_db_sa/ibm_db.py

@zzzeek fyi

**Comment by raguks** [comment]
@zzzeek Please refer to https://github.com/ibmdb/node-ibm_db/issues/167#issuecomment-408067354

**Comment by abhi7436** [comment]
Fix merged in Git. Will close this issue.
