### ISSUE TITLE
PyPI package is outdated

### ISSUE THREAD

**Issue by benjaminsingleton** [ibmdb/python-ibmdbsa#45]
Given that there have been 6 commits since the 8/31/2016 release, is there a reason that the package hasn't been uploaded to [PyPI](https://pypi.org/project/ibm_db_sa/)? I tend to install via `pip` but that doesn't get me the current state of the package.

**Comment by hemlatabhatt** [comment]
Ibm_db_sa latest release 0.3.4 is available in pypi ,hence closing this

**Comment by benjaminsingleton** [comment]
Great, thank you! Small note -- README file still shows 0.3.3.

**Comment by hemlatabhatt** [comment]
@benjaminsingleton ,yes will plan to fix this soon with couple of more issues.Thanks
