### ISSUE TITLE
ACR support

### ISSUE THREAD

**Issue by alloni-kramer-ibm** [ibmdb/python-ibmdbsa#50]
Hi - I'm working on an application that has a backing db2 on cloud DB with a remote disaster recovery node, using ibm_db_sa to connect to it.  The connection string we used is ibm_db_sa://dummy:dummy@dashdb-txn-flex-yp-dal10-37.services.dal.bluemix.net:50001/BLUDB;clientRerouteAlternateServerName=dashdb-txn-flex-yp-wdc04-13.services.dal.bluemix.net;clientRerouteAlternatePortNumber=50001;enableSeamlessACR=true;;SECURITY=SSL; .  Today, we tested the failove, and got repeated failures: "ibm_db_dbi::OperationalError: [IBM][CLI Driver] CLI0106E  Connection is closed. SQLSTATE=08003 SQLCODE=-99999 [SQL: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'] (Background on this error at: http://sqlalche.me/e/e3q8)".  Is ACR supported with ibm_db_sa?  If not, is there a workaround?

**Comment by abhi7436** [comment]
Hi @alloni-kramer-ibm ,

You can configure ACR in your db2dsdriver.cfg file. I have pasted below link which explains how to configure ACR in cfg file.
https://www.ibm.com/support/knowledgecenter/es/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056196.html

Let me know if you need any more assistance.

Thanks,
Abhinav

**Comment by alloni-kramer-ibm** [comment]
Hi - where is the db2dsdriver.cfg file?  I can't seem to find one anywhere in the filesystem.  Do I need to create one?  Where is that configured when using ibm_db_sa?

**Comment by alloni-kramer-ibm** [comment]
Or do you mean on the server side?  The server is set up with failover as normal in DB on Cloud.

**Comment by abhi7436** [comment]
Hi,
Sample db2dsdriver.cfg file is present inside cfg folder which is inside the folder where you have installed/configured DB2 Driver. If its not present then you will be required to configure this file as mentioned in above link.
Please let me know if you need any help.

Thanks,
Abhinav
