### ISSUE TITLE
ibm_db_sa 0.3.4 -import the DB API module 'No driver found for dialect 'ibm_db_sa+pyodbc400'' but failed

### ISSUE THREAD

**Issue by sidnaik03** [ibmdb/python-ibmdbsa#53]
** While creating the engine for 'ibm_db_sa+pyodbc400://u026607:*****@172.219.154.200:446/t10050bp', SQLAlchemy tried to
  ** import the DB API module 'No driver found for dialect 'ibm_db_sa+pyodbc400'' but failed.
  ********************************************************
  **  + This is because 1 of 2 reasons:
  **  1.) You forgot to install the DB API module 'No driver found for dialect 'ibm_db_sa+pyodbc400''.
  **  --> (Try: 'pip install No driver found for dialect 'ibm_db_sa+pyodbc400'')
  **  2.) If the above step fails, you most likely forgot to
  **  --> install the actual database driver on your local
  **  --> machine! The driver is needed in order to install
  **  --> the Python DB API ('No driver found for dialect 'ibm_db_sa+pyodbc400'').

**Comment by amukherjee28** [comment]
This dialect is for IBMi ODBC driver to be used with ibm_db_sa.

Please open a new issue if the issue continues to exists or you need help with respect to pyodbc400 dialect.

Thanks
