### ISSUE TITLE
CASTs get removed

### ISSUE THREAD

**Issue by jastako** [ibmdb/python-ibmdbsa#7]
Having SQLAlchemy use CASTs, causes IBM_DB_SA layer to remove them on the call to:
ibm_db_sa/base.py:351:            sql_ori = compiler.SQLCompiler.visit_select(self, select, **kwargs)

, where SQLCompiler is sqlalchemy.sql.compiler.SQLCompiler.

While 'select' input parameter is made of proper SQL query (incl. CASTs), the 'sql_ori' doesn't have it anymore (both in SELECT and WHERE clauses).

Example:
select is "SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1"
sql_ori is "SELECT 'test plain returns' AS anon_1 FROM SYSIBM.SYSDUMMY1"

**Comment by dr-leo** [comment]
I have the same result with the Python3 port by rredburn (PR8). Had to fall back to text() which is a nightmare.

**Comment by amukherjee28** [comment]
With the new version of sqlalchemy and support from ibm_db_sa this needs to be checked.
Python3 supported in already in place.
Please open a new issue in case this still remains as a concerned issue.

**Comment by amukherjee28** [comment]
With the new version of sqlalchemy and support from ibm_db_sa this needs to be checked.
Python3 supported in already in place.
Please open a new issue in case this still remains as a concerned issue.
