### ISSUE TITLE
Trouble using credentials for SSL connection with flask-sqlalchemy

### ISSUE THREAD

**Issue by data-henrik** [ibmdb/python-ibmdbsa#70]
I am trying to initialize a connection to Db2 Warehouse on Cloud by setting SQLALCHEMY_DATABASE_URI to one of the provided credential parts. They look like this:
```

{
  "hostname": "db2w-host.us-south.db2w.cloud.ibm.com",
  "password": "passwd",
  "https_url": "https://db2w-host.us-south.db2w.cloud.ibm.com",
  "port": 50001,
  "ssldsn": "DATABASE=BLUDB;HOSTNAME=db2w-host.us-south.db2w.cloud.ibm.com;PORT=50001;PROTOCOL=TCPIP;UID=bluadmin;PWD=passwd;Security=SSL;",
  "host": "db2w-host.us-south.db2w.cloud.ibm.com",
  "uri": "db2://bluadmin:passwd@db2w-host.us-south.db2w.cloud.ibm.com:50001/BLUDB?ssl=true;",
  "db": "BLUDB",
  "username": "bluadmin",
  "ssljdbcurl": "jdbc:db2://db2w-host.us-south.db2w.cloud.ibm.com:50001/BLUDB:sslConnection=true;"
}
```
I tried **ssldsn** and **uri**, but both result in errors. What is the correct connection URI? Could you

- [ ] improve the documentation and add more examples with SSL connections
- [ ] support direct consumption of credentials coming from Db2 services

**Comment by shreyas-shankar** [comment]
@data-henrik Were you able to get any help for this issue?

**Comment by data-henrik** [comment]
AFAIK it is open

**Comment by amukherjee28** [comment]
Hi,

For Sql Alchemy can you need to use the URI syntax for connection.
Also while providing the URI
"uri": "db2://bluadmin:passwd@db2w-host.us-south.db2w.cloud.ibm.com:50001/BLUDB?ssl=true;",

Can you please check after changing the dialect from db2 to ibm_db_sa
ibm_db_sa://bluadmin:passwd@db2w-host.us-south.db2w.cloud.ibm.com:50001/BLUDB?ssl=true

can you try once with the above mentioned URI.

Thanks.

**Comment by amukherjee28** [comment]
Hi,

Just wanted to check if the above solution provided worked for you or you still have the issue seen.

Can you please let me know.

Thanks.

**Comment by shreyas-shankar** [comment]
Sorry for the late reply.

Your suggestion worked. Thanks for the help!
