### ISSUE TITLE
Add ibm_db_sa to conda-forge

### ISSUE THREAD

**Issue by PeterFogh** [ibmdb/python-ibmdbsa#71]
I just found out that ibm_db now is available on conda-force https://anaconda.org/conda-forge/ibm_db. 
Are there plans for adding ibm_db_sa to conda-forge?

**Comment by amukherjee28** [comment]
This has been addressed 

https://anaconda.org/conda-forge/ibm_db_sa/files

Please let me know if this can be closed.
