### ISSUE TITLE
update multiple not raising IntegrityError

### ISSUE THREAD

**Issue by mdobrzanski** [ibmdb/python-ibmdbsa#75]
Exception ibm_db_dbi.Error is raised instead of IntegrityError when updating multiple objects. Works fine when updating single object. 

Here's some code to reproduce. In second try IntegrityError was not raised.

```
from sqlalchemy import create_engine, Column, Integer
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

connstr = 'db2://chinook:p4ssw0rd@localhost:50000/Chinook'
engine = create_engine(connstr)
Base = declarative_base()

class Item(Base):
    __tablename__ = 'item'
    id = Column(Integer, primary_key=True)

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

session.add_all([
    Item(id=1),
    Item(id=2),
    Item(id=3),
    Item(id=4)
])
session.commit()

query = session.query(Item).filter(Item.id > 1)

item2 = query.first()
item2.id = 1
try:
    session.commit()
except IntegrityError as exc:
    print exc
    print 'expected error'
finally:
    session.rollback()


print '----'


items = query.all()
for i in items:
    i.id = 1

try:
    session.commit()
except IntegrityError as exc:
    print exc
    print 'expected error'
except Exception as exc:
    print exc
    print 'unexpected error'
finally:
    session.rollback()
```

The above code is updating PK to already present in table and database returns error 803. 

When updating single object a nice IntegrityError is raised. That is correct.

> (ibm_db_dbi.IntegrityError) ibm_db_dbi::IntegrityError: Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "CHINOOK.Invoice" from having duplicate values for the index key.  SQLSTATE=23505 SQLCODE=-803 [SQL: u'UPDATE "Invoice" SET "InvoiceId"=? WHERE "Invoice"."InvoiceId" = ?'] [parameters: (1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

But when updating PK of multiple objects in the same session we get general Error instead of IntegrityError

> (ibm_db_dbi.Error) ibm_db_dbi::Error: 
Error 1: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "CHINOOK.Invoice" from having duplicate values for the index key.  SQLSTATE=23505 SQLCODE=-803 
> 
> Error 2: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "CHINOOK.Invoice" from having duplicate values for the index key.  SQLSTATE=23505 SQLCODE=-803 
 [SQL: u'UPDATE "Invoice" SET "InvoiceId"=? WHERE "Invoice"."InvoiceId" = ?'] [parameters: ((1, 2), (1, 3))] (Background on this error at: http://sqlalche.me/e/dbapi)

**Comment by imavo** [comment]
Do you still have this issue?  I cannot recreate with Python 3.6.8, ibm_db_sa  v0.3.5, sqlalchemy  1.3.16 . I get IntegrityError in both cases.

**Comment by kotofos** [comment]
Reproduced on Python 3.7.8; ibm_db_sa 0.3.5; sqlalchemy 1.3.19; DB2 v10.5.0.5. ibm_db_dbi.Error in second case.

**Comment by kotofos** [comment]
I think problem in idm-db itself.
In execute single there is `self.messages.append(_get_exception(inst))`. But in in executemany there is `self.messages.append(Error(inst))`

see
https://github.com/ibmdb/python-ibmdb/blob/778f63228517040ca5c3d4c3d77589116c635c9e/IBM_DB/ibm_db/ibm_db_dbi.py#L1282
and https://github.com/ibmdb/python-ibmdb/blob/778f63228517040ca5c3d4c3d77589116c635c9e/IBM_DB/ibm_db/ibm_db_dbi.py#L1427

**Comment by imavo** [comment]
I can recreate with python 3.6.8 and ibm_db v3.0.2 and ibm-db-sa 0.3.5.

Please open a ticket for ibm_db  python module at  https://github.com/ibmdb/python-ibmdb/issues

You can also create a PR, and if the maintainers agrees then your changed would be merged into the next release.

**Comment by amukherjee28** [comment]
This is indeed bug in the ibm_db_dbi code for executemany where in when an error is encountered the appending of the error message is wrapped into the function Error instead of _get_execption.
Changing the same to ```self.messages.append(_get_exception(inst))``` does solve the issue.

```
2022-04-26 05:55:21,277 INFO sqlalchemy.engine.Engine [dialect ibm_db_sa+ibm_db_sa does not support caching 0.00141s] (1,)
2022-04-26 05:55:21,281 INFO sqlalchemy.engine.Engine UPDATE item SET id=? WHERE item.id = ?
2022-04-26 05:55:21,282 INFO sqlalchemy.engine.Engine [dialect ibm_db_sa+ibm_db_sa does not support caching 0.00029s] ((1, 3), (1, 4), (1, 10))
2022-04-26 05:55:21,291 INFO sqlalchemy.engine.Engine ROLLBACK
(ibm_db_dbi.IntegrityError) ibm_db_dbi::IntegrityError: Error 1: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "NEWTON.ITEM" from having duplicate values for the index key.  SQLSTATE=23505  SQLCODE=-803\nError 2: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "NEWTON.ITEM" from having duplicate values for the index key.  SQLSTATE=23505  SQLCODE=-803\nError 3: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "NEWTON.ITEM" from having duplicate values for the index key.  SQLSTATE=23505  SQLCODE=-803\n
[SQL: UPDATE item SET id=? WHERE item.id = ?]
[parameters: ((1, 3), (1, 4), (1, 10))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
expected error
```

This does the change the expection.

**Comment by bchoudhary6415** [comment]
@mdobrzanski can you please give update on this issue?
