### ISSUE TITLE
Support for connection to DB2 Z/OS - Mainframe

### ISSUE THREAD

**Issue by ashish1987gupta** [ibmdb/python-ibmdbsa#86]
It doesn’t look like that this version supports connection to DB2 for Z/OS. Is there any plan to enhance the adapter with this support ? If so, by when can it be expected ?

**Comment by amukherjee28** [comment]
Hi @ashish1987gupta 

Currently the ORM support is only for DB2/LUW server only.
For Mainframe Support (DB2 on ZOS) we would require a business justification so that we can prioritise the same and work on it.

Thanks.

**Comment by ashish1987gupta** [comment]
Hi @amukherjee28 

There is a business requirement where the data needs to be on the mainframe db2 table (say z_table_1) as it is required by legacy calculation programs, which are on mainframe. But need to create a new UI for the users to view and modify the data present on the table z_table_1. Planning to use Python-Flask for rapid development but without SQLAlchemy DB2 adapter support, it is not able to connect to Mainframe DB2. Hence it is a blocker.

**Comment by amukherjee28** [comment]
Hi @ashish1987gupta 

Thank you for you feedback. We understand you have a requirement from you end to support mainframe connections and transactions. Also we have to analyse the same from our end to see what needs to be done to support the same.

Meanwhile just wanted to know, do you have DB2Connect License to connect to mainframe?

Thanks.

**Comment by ashish1987gupta** [comment]
Hi @amukherjee28 

Yes, have the db2connect license. Can connect to DB2 Mainframe directly using the python libraries but not through SQLAlchemy. The other solution that I am thinking might be to prepare and execute sqls using python db2 connection until the SQLAlchemy adapter is able to provide ORM capabilities. Let me know your thoughts.

**Comment by amukherjee28** [comment]
Hi @ashish1987gupta 

Since you already have the DB2Connect ZOS license, it would be a good thing to proceed with the queries directory using PYTHON Capability.
Mean while we are adding this item to our backlog list to check what needs to be done to support Mainframe with SQL Adaptor.

Thanks.

**Comment by ashish1987gupta** [comment]
Sounds good. thank you! with ORM capabilities, developers can treat DB2 on Z/OS same as distributed DB2. And this will ease in web design and moving away from traditional cics screens. 

Thanks Much!

**Comment by arun-krishnamoorthy** [comment]
Hi Guys,
What about the version of ibm sa adapter here ,https://pypi.org/project/ibm-db-sa-py3/ ,it seems to support DB2 over Z/os using ibm_db driver support?

- Remote connections to z/OS (DB2 UDB for zOS), only by default ibm_db drivers

Could you please clarify?

**Comment by amukherjee28** [comment]
Hi @arun-krishnamoorthy 

I checked the link and it points to native Python Driver (IBM_DB) when you try to download.
And the home page points to the same Alchemy adaptor that we have.

We are currently working on supporting ZOS with the Alchemy adaptor and will update you soon on the progress.

Thanks.

**Comment by amukherjee28** [comment]
Hi,

I have pushed the latest code to Support ZOS connection with IBM_DB_SA into a development branch.
I request you to try out the new code and let me know if it works for you till the time we make an official release with the changes.

You can get the new code from the branch dev_zos_support.
https://github.com/ibmdb/python-ibmdbsa/tree/dev_zos_support

Please let me know in case you have any more queries.

Thanks.

**Comment by rafpyprog** [comment]
> Hi,
> 
> I have pushed the latest code to Support ZOS connection with IBM_DB_SA into a development branch.
> I request you to try out the new code and let me know if it works for you till the time we make an official release with the changes.
> 
> You can get the new code from the branch dev_zos_support.
> https://github.com/ibmdb/python-ibmdbsa/tree/dev_zos_support
> 
> Please let me know in case you have any more queries.
> 
> Thanks.

@amukherjee28  I've tested and the dev branch with ZOS without any problems.  Whats the schedule for the next release?

**Comment by amukherjee28** [comment]
Hi,

New release made with all the necessary changes.
Version : 0.3.6

Thanks.
