### ISSUE TITLE
AttributeError: 'AS400Reflector' object has no attribute 'get_unique_constraints'

### ISSUE THREAD

**Issue by brady-vitrano** [ibmdb/python-ibmdbsa#9]
I was trying to use table reflection on AS400 tables with this package and received an AttributeError.

Steps to reproduce:

``` python
engine = create_engine('db2+zxjdbc400://user:pass@as400;prompt=false')
quote_reflected = Table('MYTABLE', metadata, autoload=True, autoload_with=engine, schema='COMPANY')
```

**Comment by amukherjee28** [comment]
I see that the linked issue has been closed and hence closing this as well.
In case the issue needs attention please raise a new one with the details of the error seen.
