### ISSUE TITLE
Listing schema names when connected to a DB2 Z/OS system throws error

### ISSUE THREAD

**Issue by shreyas-shankar** [ibmdb/python-ibmdbsa#91]
Hello

I am trying to list schemas and table in a connection to DB2 Z/OS

This is the code 
```
from sqlalchemy import inspect
inspector = inspect(engine)

schemas = inspector.get_schema_names()
tables = inspector.get_table_names(<schema>)

```

I get the following error with the code above
```
InternalError: (ibm_db_dbi.InternalError) ibm_db_dbi::InternalError: Exception('SQLNumResultCols failed: [IBM][CLI Driver][DB2] SQL0805N  Package "<database>.NULLID.SYSSH200.5359534C564C3031" was not found.  SQLSTATE=51002 SQLCODE=-805')
[SQL: SELECT DISTINCT "SYSIBM"."SYSTABLES"."CREATOR" 
FROM "SYSIBM"."SYSTABLES" 
WHERE "SYSIBM"."SYSTABLES"."CREATOR" NOT LIKE ?]
[parameters: (b'SYS%',)]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

I tried to search for this error and didn't find any obvious fixes on the client side.

The same code works with DB2 LUW. Am I missing anything here?

**Comment by amukherjee28** [comment]
Hi,

Can you provide a bit more details of the error that you see.
When I am trying to reproduce the similar thing I am able to fetch the schema names.

2021-01-12 23:55:59,897 INFO sqlalchemy.engine.base.Engine SELECT DISTINCT "SYSIBM"."SYSTABLES"."CREATOR" 
FROM "SYSIBM"."SYSTABLES" 
WHERE "SYSIBM"."SYSTABLES"."CREATOR" NOT LIKE ?
2021-01-12 23:55:59,897 INFO sqlalchemy.engine.base.Engine (b'SYS%',)
[' HLO ISPF ', 'a2src1', 'abp1943', 'abprest1', 'abptest1', 'abptest2', 'abpusm', 'adb', 'admf001', 'alcad1', 'anlqa510', 'arch5', 'aryd22db', 'aryitool', 'arytest', 'aryv21db', 'aryv31db', 'asd', 'auovr', 'b2src1', 'bbptest1', 'BCT     ', 'CARLA   ', 'ckz', 'ckzdbp13', 'ckzdbp16', 'cli', 'cliarrin', 'clibuf', 'clicfg', 'clico', 'clicobra', 'cliconv', 'clicur', 'clidesc', 'clidesc_ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss', 'clidf', 'clifp', 'clilob', 'climain', 'climain2', 'clisch', 'clitrc', 'cliuni', 'cmdb', 'colattr_ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss', 'cqm', 'cqm15128', 'cqm32ji', 'cqm32ols', 'cqm33hlo', 'cqm33ji', 'cqm3part', 'cqmddl32', 'cqmddl33', 'cqmdkst1', 'cqmmin33', 'cqmmncji', 'cqmo', 'cqmold33', 'cqmpd7', 'cqmpds', 'cqmqa', 'cqmstc', 'cqmtool1', 'cqmtools', 'cqmtoolz', 'cqmttt2', 'cqmuser', 'cricket', 'CSBAHA  ', 'CSBELK  ', 'CSBELKA ', 'CSBROW  ', 'CSCARLA ', 'cschapa', 'csgeora', 'cshloqa', 'cslividb', 'csmark', 'csryzh', 'csryzha', 'cstros', 'd30', 'db2admin', 'db2ai', 'db2oe', 'db2osc', 'db2osca', 'dbhlohal', 'dlc', 'dmh', 'drl', 'drlsys', 'dsjobmgr', 'DSN8    ', 'dsn8bqry', 'DSNACC  ', 'dsnaqt', 'dssched', 'dsshsv1', 'etitst', 'etiv44tb', 'etiv45tb', 'ggc', 'glwsamp', 'H L O ISPF', 'HAAQA   ', 'healthmetrics', 'hl1035', 'hl10354', 'hl1035a', 'hl1035b', 'hl1035c', 'hl1035d', 'hl1311db', 'hldbarca', 'hldbarcb', 'hldeflt', 'hldisc', 'hlfloat', 'hlld0063', 'hlld0064', 'hlld0065', 'hlld0066', 'hlld0067', 'hlng0031', 'hlo0540', 'hlo0641', 'hlo0659', 'hlo0710', 'hlo0730', 'hlo1092', 'hlo1105', 'hlo15', 'hlo1630', 'hlo432', 'hlo7351', 'hlo7352', 'hlo7353', 'hloarch1', 'hloarch2', 'hloarch3', 'hloarch4', 'hloarch5', 'hloarch6', 'hloarch7', 'hloarch8', 'hloarch9', 'hloispf', 'hloivpdb', 'hloivpdo', 'hlosmk', 'hlov21tb', 'hlr0097', 'hltest', 'HLTEST CREATOR NAME', 'hl_test', 'HlO iSpf', 'ibmiocm', 'ibmots', 'ibmpdq', 'IBMUSER ', 'idaaid1', 'ji14239', 'jia', 'lon', 'MFA#@QDS', 'MFAQDS#@', 'mfaqds2', 'mfaqds21', 'mvf', 'newton', 'pdbate', 'PDBORN  ', 'PDGREG  ', 'pdjoh2', 'PDKRUG  ', 'pdlisa', 'pdnjen', 'pdpota', 'PDSMIT  ', 'PDWDBB  ', 'PDWEATH ', 'PDYUHI  ', 'pk25', 'pk26', 'pk27', 'ppp', 'presrt5', 'procmgmt', 'pschema', 'pvli', 'pvltest', 'pvtest', 'pw4', 'Q       ', 'qaq', 'qatest', 'qazsxdce', 'qm000', 'qm41db', 'qmcqrstp', 'qmtest', 'qmtst000', 'qmtstb01', 'qqq', 'qqqqqqqqqqwwwwwwwwwweeeeeeeeeerrrrrrrrrrtttttt', 'qqwweerr', 'qtst001', 'qwe', 'r21090', 'rckbjt31', 'RDBI    ', 'rform08', 'rform15', 'rowformhlo15', 'rpkdad1', 'RS      ', 'rsbi', 'rsqa', 'runstats', 'samb', 'schema1', 'schtab1', 'schview1', 'ser', 'siebel', 'soko0009', 'soko001', 'soko0012', 'soko232', 'templ1', 'test', 'test1', 'test2', 'ts5465', 'ts5465a', 'ts5519', 'ts5708', 'ts5766', 'ts5769', 'ts5772', 'ts5773', 'ts5774', 'ts5791', 'ts5816', 'ts5894', 'ts5970', 'ts5977', 'ts5999', 'ts5999b', 'ts6378', 'ts6390', 'ts6391a', 'ts6721', 'ts6763', 'ts7885', 'ts7885a', 'tsapk', 'tsivca', 'tsj', 'tsjab', 'tsjai', 'tsqqz', 'tssun', 'tsvxs', 'tszxl', 'vcx', 'win', 'wsw', 'zteam', 'ZURBIE  ', 'zxc', 'arytest', 'h l o ispf']

CODE SNIPPET


from sqlalchemy import *
import ibm_db_sa

engine = create_engine('ibm_db_sa://CONNECTION STRING',echo=True)

inspector = inspect(engine)
schema = inspector.get_schema_names()
print(schema)

**Comment by shreyas-shankar** [comment]
@amukherjee28 

Thank you. This required tweaking some settings on the server and had nothing to do with ibm_db_sa. I will close this issue.
