### ISSUE TITLE
TIMESTAMP naming convention

### ISSUE THREAD

**Issue by FjedorGaede** [ibmdb/python-ibmdbsa#95]
Hi everyone,

thank you for all of the work and especially for the Db2 ZOS support! This tool is amazing and we use it now on a daily basis! 

As we are currently working on making our tools production ready, we face some "bugs" at the moment and some smaller inconveniences. We found workarounds for it, but I thought it would be very beneficial to also communicate it. :)

The first issue is very simple: The TIMESTAMP column type in our Db2 ZOS Database is named as "TIMESTMP". So the "A" is missing. We are not sure why this happens, but we assume to stick to a maximum of 8 characters. We can fix this for our use-case by adding an entry to the `ischema_names` dictionary for "TIMESTMP" with the sqlalchemy type DateTime.

`ibm_db_sa.base.ischema_names["TIMESTMP"] = DateTime`

Is this even a good workaround? Would it be a good idea to add it to the package itself, as it might be a problem other people face when working with rather old Db2 ZOS databases. This might be an improvement as this could be an instant deal breaker for some developers trying this package for the first time.

Best regards,
Fjedor

**Comment by amukherjee28** [comment]
Hi @FjedorGaede 

Thanks a lot for the detailed explanation.
Let me have a look into the request a bit more and I will let you know.

I have to check for the impact on all servers and also the testing suite as how it behaves.

Let me have a more detailed look into this and come back.

Thanks.

**Comment by amukherjee28** [comment]
As per IBM documentation for datatypes TIMESTAMP is the supported datatype.
https://www.ibm.com/docs/en/db2-for-zos/12?topic=columns-date-time-timestamp-data-types

Any modification to the datatypes or special datatypes has to be handled separately in the application code.

The above example of the code is a good way to handle any other datatypes.

Hence closing on the issue.
