### ISSUE TITLE
Version 0.3.6 in PyPi has an extraneous print statement in base.py 

### ISSUE THREAD

**Issue by afetek** [ibmdb/python-ibmdbsa#99]
In line 707 in base.py there is the following extraneous print:   `print(self.dbms_name)`

**Comment by amukherjee28** [comment]
https://github.com/ibmdb/python-ibmdb/issues/625

A similar issue was already reported.

Please have a look at the comments once.

**Comment by amukherjee28** [comment]
#https://github.com/ibmdb/python-ibmdb/issues/625

**Comment by afetek** [comment]
@amukherjee28 Ok thanks. Do you want me to close the issue?

**Comment by amukherjee28** [comment]
You can keep this open. Once I have the issue fixed in the new release you can close this.

This can help as the base defect in case there are more issues reported.

Thanks

**Comment by amukherjee28** [comment]
New version is released and this issue had been addressed in the new release 0.3.7.

Please check and let me know if this can be closed.

**Comment by afetek** [comment]
Tested the issue. Closing.
